version: '3'

services:

  web:
    build: ./project
    image: web
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - ./project:/usr/src/app
      - ./project/logs:/usr/src/app/logs
    command: gunicorn -b 0.0.0.0:8000 --log-level=info --access-logfile=logs/gunicorn_access.log --error-logfile=logs/gunicorn_error.log app:app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    image: web
    volumes:
      - ./project:/usr/src/app
      - ./project/logs:/usr/src/app/logs
    command: celery -A app.tasks worker --autoscale=10,2 --loglevel=info  --logfile=logs/celery.log
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:5.0.3-alpine

  monitor:
    image: web
    ports:
      - 5555:5555
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - web
      - redis
